version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: vault-plugin-solana
    main: ./cmd/vault-plugin-solana
    binary: vault-plugin-solana
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X version.Version={{.Version}} -X version.Commit={{.Commit}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - arm

archives:
  - id: vault-plugin-solana
    ids: [vault-plugin-solana]
    formats: ['zip']
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
      
checksum:
  algorithm: sha256
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"

signs:
  - artifacts: checksum
    cmd: gpg
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

changelog:
  disable: true
