version: 2
before:
  hooks:
    - go mod tidy
builds:
  - env:
    - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X version.Version={{.Version}} -X main.commit={{.Commit}}'
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: '386'
      - goo: windows
        goarch: arm
    binary: '{{ .ProjectName }}_v{{ .Version }}'
  archives:
  - format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
  checksum:
    algorithm: sha256
    name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  release:
    draft: true
  changelog:
    skip: true
